repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        types: [python]
        language_version: python3.8
        # args: ['--check', '--diff', 'tests']
