# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

sudo: false
python:
  - "3.7"
  - "3.6"
  - "3.5"

env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.0

before_install:
  - pip install -r requirements-test.txt
  - python --version

install:
  - python setup.py develop
  - pip install -q django==$DJANGO_VERSION
  - python --version

script:
  - python setup.py test

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=2.0
