dist: xenial
language: python
sudo: false
python:
  - '3.7'
  - '3.6'
  - '3.5'

env:
  matrix:
    - DJANGO_VERSION=2.2
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.0
  global:
    secure: fo8WUfD96kzjPChKvHXN16wpjPJpB+BwCESZ//Ayr41geDymhDdvz1apTISwPuuecQN2ZJHylGaGE1ccNI6Sn6giJUrd36FjV+w+hh8LysiNp7cIyQ7jpcYZVoxKO0pI3baikr8BMhuN+kv/vWfti5K5eyQctjUD6r1a8Ft+fW4W104zsnWyCxIpnvO7xnRJBU2d6Ga3AyGmGnyGDPWjDeADKlJ1k9+f0/3KHI2utswvAJpOEPkDFzubneXvwc5OnF6mYgsL8yMWSUyPBNzVah7+24M+jMoPQ1qqWSNvYnjR22aoYVbUQx1nqDL+E+w3kornLea6OaoHOABtxCBYMpc+5qGS8dCY95BfD779hPOikJz78zcazgfc46XRr0NJ2sdUkcqUzE0B/hVMoTr7qzcL8TsMkJlShubJTcoZDi8rIKivj2ddVN3HQLHwbop3eMKWpELo/M1Wqsk1YDGf3R30WN0w9ey70nvLuNvYnlVclOc2rBlt4AU2fWzpp37jzlPf5Pmdt/XKENYtxeI+QH92QPYewZ5KlwbcNUEScNk3ZHKRHVQAZB9lVQM1Ag1dY0D5RIx7HSBwgVlzmZsS6lKfKl7Gvq0ogkEzlDju7gTJ8KGqsWzQ7l8ihhCFf/7gW29Pv8cZk40kri5quzllw9HdlmCVEZ/Qd9wKhHs8FXU=

before_install:
  - pip install -r requirements-test.txt
  - python --version

install:
  - python setup.py develop
  - pip install -q django==$DJANGO_VERSION
  - python --version

script:
  - python setup.py test
  - coverage html

after_success:
  - codecov

matrix:
  exclude:
    - python: '3.5'
      env: DJANGO_VERSION=2.0
