name: Create a release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - develop
      # - master

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: get-py-package-version
        run: echo VERSION=`python setup.py --version` >> $GITHUB_ENV

      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: 🚀 release
          PACKAGE_VERSION: v${{ env.VERSION }}
          # NPM_VERSION: v${{ steps.package-version.outputs.current-version}}
          GIT_PR_RELEASE_TEMPLATE: .github/.git-pr-release-template
