name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]
  push:
    branches:
      - develop
      - master

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: get-py-package-version
        run: echo VERSION=`python setup.py --version` >> $GITHUB_ENV

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Create a release pull request
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          # GIT_PR_RELEASE_BRANCH_PRODUCTION: release-${{ env.VERSION }}
          # GIT_PR_RELEASE_BRANCH_STAGING: develop
          # GIT_PR_RELEASE_LABELS: release
          # PACKAGE_VERSION: v${{ env.VERSION }}
          # GIT_PR_RELEASE_TEMPLATE: .github/.git-pr-release-template

          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: master
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          gem install -N git-pr-release -v "1.2.0"
          git-pr-release --no-fetch

        # env:
        #   GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        #   GIT_PR_RELEASE_BRANCH_STAGING: ${{ steps.vars.outputs.branch_name }}
        #   GIT_PR_RELEASE_LABELS: ${{ steps.vars.outputs.branch_prefix }}
        #   GIT_PR_RELEASE_TITLE: "[ReleasePR] ${{ steps.vars.outputs.branch_name }}"
        #   GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template