name: Create Release

on:
  pull_request:
    branches:
      - master
    types: [closed]
  push:
    branches:
      - develop
      - master

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: get-py-package-version
        run: |
          echo VERSION=`python setup.py --version` >> $GITHUB_ENV

        # run: |
        #   VERSION=`python setup.py --version`
        #   export $VERSION
        #   env|grep VERSION

      - name: Create a release pull request
        uses: bakunyo/git-pr-release-action@master
        run: |
          echo "${{ env.VERSION }}"
          echo ${{ secrets.GITHUB_TOKEN }}
        # env:
        #   GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        #   GIT_PR_RELEASE_BRANCH_STAGING: ${{ steps.vars.outputs.branch_name }}
        #   GIT_PR_RELEASE_LABELS: ${{ steps.vars.outputs.branch_prefix }}
        #   GIT_PR_RELEASE_TITLE: "[ReleasePR] ${{ steps.vars.outputs.branch_name }}"
        #   GIT_PR_RELEASE_TEMPLATE: .git-pr-release-template