on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.JP_BIRTHDAY_TOKEN }}
      ACTOR: ${{ github.actor }}
      REPOSITORY: $(echo ${{ github.repository }} | sed -e "s#.*/##")
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: update CHANGELOG
        run: |
          gem install github_changelog_generator
          echo ${{ env.TOKEN }}
          echo ${{ env.REPOSITORY }}
          echo ${{ env.ACTOR }}
          
          github_changelog_generator -u ${{ env.ACTOR }} \
                                    -p ${{ env.REPOSITORY }} \
                                    --header-label '# HISTORY' \
                                    -t ${{ env.TOKEN }}

          cat CHANGELOG.md

      - name: push develop
        run: |
          ls -la
