on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.JP_BIRTHDAY_TOKEN }}
      REPOSITORY: $(echo ${{ github.repository }} | sed -e "s#.*/##")
      ACTOR: ${{ github.actor }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: update CHANGELOG
        run: |
          gem install github_changelog_generator
          echo ${{ env.TOKEN }}
          echo ${{ env.REPOSITORY }}
          echo ${{ env.ACTOR }}

          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo $REPOSITORY

          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF
          echo ${{ github.actor }}
          echo ${{ github.repository }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.base_ref }}

# github_changelog_generator -u shimakaze-git -p django-jp-birthday --header-label '# HISTORY'
# github_changelog_generator -t <token>
