on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: tox
      # - run: python -m pip install pipenv
      # - run: python -m pipenv sync --dev
      # - run: python -m pipenv run coverage_xml
      - uses: codecov/codecov-action@v2
        with:
          name: codecov-umbrella # optional

          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          # files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

# - name: Codecov
#   uses: codecov/codecov-action@v2.1.0

# - name: Codecov
#   uses: codecov/codecov-action@v1.5.2
#   with:
#     file: ./coverage.lcov
#     fail_ci_if_error: true

# steps:
# - uses: actions/checkout@master
# - uses: codecov/codecov-action@v2
#   with:
#     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#     files: ./coverage1.xml,./coverage2.xml # optional
#     flags: unittests # optional
#     name: codecov-umbrella # optional
#     fail_ci_if_error: true # optional (default = false)
#     verbose: true # optional (default = false)

# # Codecovにアップロード
# - name: Codecov
#   uses: codecov/codecov-action@v1.5.2
#   with:
#     file: ./coverage.lcov
#     fail_ci_if_error: true

# - name: upload coverage
#   uses: codecov/codecov-action@v1
#   with:
#     token: ${{ secrets.CODECOV_TOKEN }}
